[package]
name = "moon_local"
version = "1.0.0"
edition = "2021"

[dependencies]
moon_core = { path = "moon_core" }
tokio = { version = "1", features = ["full"] }

[[bin]]
name = "moon_full_node"
path = "moon_full_node/src/main.rs"
